apiVersion: v1
kind: Template
labels:
  template: ${APPNAME}-build-config-template
metadata:
  annotations:
    description: ITAC gerneric template for docker strategy based build
    tags: docker,itac,general
  name: ${APPNAME}-bc
objects:
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: ${APPNAME}
    namespace: ${NAMESPACE}
    labels:
      build: ${APPNAME}
      app: ${APPNAME}
  spec:
    lookupPolicy:
      local: false
    tags:
      - name: ${TAG}
        from:
          kind: DockerImage
          name: ${REGISTRY_URL}${APPNAME}:${TAG}
        importPolicy: {}
        referencePolicy:
          type: Source
- apiVersion: v1
  kind: BuildConfig
  metadata:
    name: ${APPNAME}
    namespace: ${NAMESPACE}
    labels:
      build: ${APPNAME}
  spec:
    nodeSelector: null
    output:
      to:
        kind: DockerImage
        name: ${REGISTRY_URL}${APPNAME}:${TAG}
    resources: {}
    strategy:
      type: Docker
      dockerStrategy: {}
    postCommit: {}
    source:
      type: Binary
      binary: {}
parameters:
- name: APPNAME
  description: application name 
  required: true
- name: NAMESPACE
  description: openshift project name or namespace
  value: 'devops-tools'
- name: REGISTRY_URL
  description: registry url for publishing the image i.e. openshift by default
  value: ''
- name: TAG
  description: image tag
  value: 'latest'
